//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace NIS.CARESCAPEGateway {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CARESCAPEGatewaySoap", Namespace="http://mayaminer.com/CARESCAPEGateway/")]
    public partial class CARESCAPEGateway : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetEKG_IMG_LEADOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEKG_IMGOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CARESCAPEGateway() {
            this.Url = global::NIS.Properties.Settings.Default.NIS_CARESCAPEGateway_CARESCAPEGateway;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetEKG_IMG_LEADCompletedEventHandler GetEKG_IMG_LEADCompleted;
        
        /// <remarks/>
        public event GetEKG_IMGCompletedEventHandler GetEKG_IMGCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mayaminer.com/CARESCAPEGateway/GetEKG_IMG_LEAD", RequestNamespace="http://mayaminer.com/CARESCAPEGateway/", ResponseNamespace="http://mayaminer.com/CARESCAPEGateway/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEKG_IMG_LEAD(string FEENO, string STARTDATE, string ENDDATE, string LEAD) {
            object[] results = this.Invoke("GetEKG_IMG_LEAD", new object[] {
                        FEENO,
                        STARTDATE,
                        ENDDATE,
                        LEAD});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEKG_IMG_LEADAsync(string FEENO, string STARTDATE, string ENDDATE, string LEAD) {
            this.GetEKG_IMG_LEADAsync(FEENO, STARTDATE, ENDDATE, LEAD, null);
        }
        
        /// <remarks/>
        public void GetEKG_IMG_LEADAsync(string FEENO, string STARTDATE, string ENDDATE, string LEAD, object userState) {
            if ((this.GetEKG_IMG_LEADOperationCompleted == null)) {
                this.GetEKG_IMG_LEADOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEKG_IMG_LEADOperationCompleted);
            }
            this.InvokeAsync("GetEKG_IMG_LEAD", new object[] {
                        FEENO,
                        STARTDATE,
                        ENDDATE,
                        LEAD}, this.GetEKG_IMG_LEADOperationCompleted, userState);
        }
        
        private void OnGetEKG_IMG_LEADOperationCompleted(object arg) {
            if ((this.GetEKG_IMG_LEADCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEKG_IMG_LEADCompleted(this, new GetEKG_IMG_LEADCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mayaminer.com/CARESCAPEGateway/GetEKG_IMG", RequestNamespace="http://mayaminer.com/CARESCAPEGateway/", ResponseNamespace="http://mayaminer.com/CARESCAPEGateway/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEKG_IMG(string FEENO, string STARTDATE, string ENDDATE) {
            object[] results = this.Invoke("GetEKG_IMG", new object[] {
                        FEENO,
                        STARTDATE,
                        ENDDATE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEKG_IMGAsync(string FEENO, string STARTDATE, string ENDDATE) {
            this.GetEKG_IMGAsync(FEENO, STARTDATE, ENDDATE, null);
        }
        
        /// <remarks/>
        public void GetEKG_IMGAsync(string FEENO, string STARTDATE, string ENDDATE, object userState) {
            if ((this.GetEKG_IMGOperationCompleted == null)) {
                this.GetEKG_IMGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEKG_IMGOperationCompleted);
            }
            this.InvokeAsync("GetEKG_IMG", new object[] {
                        FEENO,
                        STARTDATE,
                        ENDDATE}, this.GetEKG_IMGOperationCompleted, userState);
        }
        
        private void OnGetEKG_IMGOperationCompleted(object arg) {
            if ((this.GetEKG_IMGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEKG_IMGCompleted(this, new GetEKG_IMGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetEKG_IMG_LEADCompletedEventHandler(object sender, GetEKG_IMG_LEADCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEKG_IMG_LEADCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEKG_IMG_LEADCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetEKG_IMGCompletedEventHandler(object sender, GetEKG_IMGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEKG_IMGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEKG_IMGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591