//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace NIS.EMRReference {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EMRExchangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::NIS.Properties.Settings.Default.NIS_EMRReference_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EMRExchangeCompletedEventHandler EMRExchangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EMRExchange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EMRExchange(string HospitalNHIID, string HospitalName, string DocDKind, string OrderNO, string GenDocDate, string PatientName, string PatientID, string Gender, string ChartNo, string PhysicianID, string PhysicianName, string Confidentiality, string CDAXml, out string ErrMsg) {
            object[] results = this.Invoke("EMRExchange", new object[] {
                        HospitalNHIID,
                        HospitalName,
                        DocDKind,
                        OrderNO,
                        GenDocDate,
                        PatientName,
                        PatientID,
                        Gender,
                        ChartNo,
                        PhysicianID,
                        PhysicianName,
                        Confidentiality,
                        CDAXml});
            ErrMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EMRExchangeAsync(string HospitalNHIID, string HospitalName, string DocDKind, string OrderNO, string GenDocDate, string PatientName, string PatientID, string Gender, string ChartNo, string PhysicianID, string PhysicianName, string Confidentiality, string CDAXml) {
            this.EMRExchangeAsync(HospitalNHIID, HospitalName, DocDKind, OrderNO, GenDocDate, PatientName, PatientID, Gender, ChartNo, PhysicianID, PhysicianName, Confidentiality, CDAXml, null);
        }
        
        /// <remarks/>
        public void EMRExchangeAsync(string HospitalNHIID, string HospitalName, string DocDKind, string OrderNO, string GenDocDate, string PatientName, string PatientID, string Gender, string ChartNo, string PhysicianID, string PhysicianName, string Confidentiality, string CDAXml, object userState) {
            if ((this.EMRExchangeOperationCompleted == null)) {
                this.EMRExchangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEMRExchangeOperationCompleted);
            }
            this.InvokeAsync("EMRExchange", new object[] {
                        HospitalNHIID,
                        HospitalName,
                        DocDKind,
                        OrderNO,
                        GenDocDate,
                        PatientName,
                        PatientID,
                        Gender,
                        ChartNo,
                        PhysicianID,
                        PhysicianName,
                        Confidentiality,
                        CDAXml}, this.EMRExchangeOperationCompleted, userState);
        }
        
        private void OnEMRExchangeOperationCompleted(object arg) {
            if ((this.EMRExchangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EMRExchangeCompleted(this, new EMRExchangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void EMRExchangeCompletedEventHandler(object sender, EMRExchangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EMRExchangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EMRExchangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591