//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace NIS.WebService_RCS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceRCSSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceRCS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRCSSystemURLFromIPDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRCSSystemURLFromIPDByResultModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRCSSystemURLFromOPDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRCSSystemURLFromOPDByResultModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInHistoryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceRCS() {
            this.Url = global::NIS.Properties.Settings.Default.NIS_WebService_RCS_WebServiceRCS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetRCSSystemURLFromIPDCompletedEventHandler GetRCSSystemURLFromIPDCompleted;
        
        /// <remarks/>
        public event GetRCSSystemURLFromIPDByResultModeCompletedEventHandler GetRCSSystemURLFromIPDByResultModeCompleted;
        
        /// <remarks/>
        public event GetRCSSystemURLFromOPDCompletedEventHandler GetRCSSystemURLFromOPDCompleted;
        
        /// <remarks/>
        public event GetRCSSystemURLFromOPDByResultModeCompletedEventHandler GetRCSSystemURLFromOPDByResultModeCompleted;
        
        /// <remarks/>
        public event GetInHistoryCompletedEventHandler GetInHistoryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRCSSystemURLFromIPD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRCSSystemURLFromIPD(string UserID, string AdmitNo) {
            object[] results = this.Invoke("GetRCSSystemURLFromIPD", new object[] {
                        UserID,
                        AdmitNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromIPDAsync(string UserID, string AdmitNo) {
            this.GetRCSSystemURLFromIPDAsync(UserID, AdmitNo, null);
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromIPDAsync(string UserID, string AdmitNo, object userState) {
            if ((this.GetRCSSystemURLFromIPDOperationCompleted == null)) {
                this.GetRCSSystemURLFromIPDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRCSSystemURLFromIPDOperationCompleted);
            }
            this.InvokeAsync("GetRCSSystemURLFromIPD", new object[] {
                        UserID,
                        AdmitNo}, this.GetRCSSystemURLFromIPDOperationCompleted, userState);
        }
        
        private void OnGetRCSSystemURLFromIPDOperationCompleted(object arg) {
            if ((this.GetRCSSystemURLFromIPDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRCSSystemURLFromIPDCompleted(this, new GetRCSSystemURLFromIPDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRCSSystemURLFromIPDByResultMode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult GetRCSSystemURLFromIPDByResultMode(string UserID, string AdmitNo) {
            object[] results = this.Invoke("GetRCSSystemURLFromIPDByResultMode", new object[] {
                        UserID,
                        AdmitNo});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromIPDByResultModeAsync(string UserID, string AdmitNo) {
            this.GetRCSSystemURLFromIPDByResultModeAsync(UserID, AdmitNo, null);
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromIPDByResultModeAsync(string UserID, string AdmitNo, object userState) {
            if ((this.GetRCSSystemURLFromIPDByResultModeOperationCompleted == null)) {
                this.GetRCSSystemURLFromIPDByResultModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRCSSystemURLFromIPDByResultModeOperationCompleted);
            }
            this.InvokeAsync("GetRCSSystemURLFromIPDByResultMode", new object[] {
                        UserID,
                        AdmitNo}, this.GetRCSSystemURLFromIPDByResultModeOperationCompleted, userState);
        }
        
        private void OnGetRCSSystemURLFromIPDByResultModeOperationCompleted(object arg) {
            if ((this.GetRCSSystemURLFromIPDByResultModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRCSSystemURLFromIPDByResultModeCompleted(this, new GetRCSSystemURLFromIPDByResultModeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRCSSystemURLFromOPD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRCSSystemURLFromOPD(string UserID, string CliniDate, string ChartNo, string DuplicateNo) {
            object[] results = this.Invoke("GetRCSSystemURLFromOPD", new object[] {
                        UserID,
                        CliniDate,
                        ChartNo,
                        DuplicateNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromOPDAsync(string UserID, string CliniDate, string ChartNo, string DuplicateNo) {
            this.GetRCSSystemURLFromOPDAsync(UserID, CliniDate, ChartNo, DuplicateNo, null);
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromOPDAsync(string UserID, string CliniDate, string ChartNo, string DuplicateNo, object userState) {
            if ((this.GetRCSSystemURLFromOPDOperationCompleted == null)) {
                this.GetRCSSystemURLFromOPDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRCSSystemURLFromOPDOperationCompleted);
            }
            this.InvokeAsync("GetRCSSystemURLFromOPD", new object[] {
                        UserID,
                        CliniDate,
                        ChartNo,
                        DuplicateNo}, this.GetRCSSystemURLFromOPDOperationCompleted, userState);
        }
        
        private void OnGetRCSSystemURLFromOPDOperationCompleted(object arg) {
            if ((this.GetRCSSystemURLFromOPDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRCSSystemURLFromOPDCompleted(this, new GetRCSSystemURLFromOPDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRCSSystemURLFromOPDByResultMode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceResult GetRCSSystemURLFromOPDByResultMode(string UserID, string CliniDate, string ChartNo, string DuplicateNo) {
            object[] results = this.Invoke("GetRCSSystemURLFromOPDByResultMode", new object[] {
                        UserID,
                        CliniDate,
                        ChartNo,
                        DuplicateNo});
            return ((ServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromOPDByResultModeAsync(string UserID, string CliniDate, string ChartNo, string DuplicateNo) {
            this.GetRCSSystemURLFromOPDByResultModeAsync(UserID, CliniDate, ChartNo, DuplicateNo, null);
        }
        
        /// <remarks/>
        public void GetRCSSystemURLFromOPDByResultModeAsync(string UserID, string CliniDate, string ChartNo, string DuplicateNo, object userState) {
            if ((this.GetRCSSystemURLFromOPDByResultModeOperationCompleted == null)) {
                this.GetRCSSystemURLFromOPDByResultModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRCSSystemURLFromOPDByResultModeOperationCompleted);
            }
            this.InvokeAsync("GetRCSSystemURLFromOPDByResultMode", new object[] {
                        UserID,
                        CliniDate,
                        ChartNo,
                        DuplicateNo}, this.GetRCSSystemURLFromOPDByResultModeOperationCompleted, userState);
        }
        
        private void OnGetRCSSystemURLFromOPDByResultModeOperationCompleted(object arg) {
            if ((this.GetRCSSystemURLFromOPDByResultModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRCSSystemURLFromOPDByResultModeCompleted(this, new GetRCSSystemURLFromOPDByResultModeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetInHistory(string ChartNo) {
            object[] results = this.Invoke("GetInHistory", new object[] {
                        ChartNo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetInHistoryAsync(string ChartNo) {
            this.GetInHistoryAsync(ChartNo, null);
        }
        
        /// <remarks/>
        public void GetInHistoryAsync(string ChartNo, object userState) {
            if ((this.GetInHistoryOperationCompleted == null)) {
                this.GetInHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInHistoryOperationCompleted);
            }
            this.InvokeAsync("GetInHistory", new object[] {
                        ChartNo}, this.GetInHistoryOperationCompleted, userState);
        }
        
        private void OnGetInHistoryOperationCompleted(object arg) {
            if ((this.GetInHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInHistoryCompleted(this, new GetInHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceResult {
        
        private System.Data.DataTable returnDataTableField;
        
        private string returnJSONField;
        
        private int dataStatusField;
        
        private string resultMsgField;
        
        /// <remarks/>
        public System.Data.DataTable returnDataTable {
            get {
                return this.returnDataTableField;
            }
            set {
                this.returnDataTableField = value;
            }
        }
        
        /// <remarks/>
        public string returnJSON {
            get {
                return this.returnJSONField;
            }
            set {
                this.returnJSONField = value;
            }
        }
        
        /// <remarks/>
        public int dataStatus {
            get {
                return this.dataStatusField;
            }
            set {
                this.dataStatusField = value;
            }
        }
        
        /// <remarks/>
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRCSSystemURLFromIPDCompletedEventHandler(object sender, GetRCSSystemURLFromIPDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRCSSystemURLFromIPDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRCSSystemURLFromIPDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRCSSystemURLFromIPDByResultModeCompletedEventHandler(object sender, GetRCSSystemURLFromIPDByResultModeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRCSSystemURLFromIPDByResultModeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRCSSystemURLFromIPDByResultModeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRCSSystemURLFromOPDCompletedEventHandler(object sender, GetRCSSystemURLFromOPDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRCSSystemURLFromOPDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRCSSystemURLFromOPDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRCSSystemURLFromOPDByResultModeCompletedEventHandler(object sender, GetRCSSystemURLFromOPDByResultModeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRCSSystemURLFromOPDByResultModeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRCSSystemURLFromOPDByResultModeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetInHistoryCompletedEventHandler(object sender, GetInHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591