//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIS.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResult", Namespace="http://10.65.1.55/teamcare/")]
    [System.SerializableAttribute()]
    public partial class ServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private NIS.ServiceReference1.ServiceResultState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public NIS.ServiceReference1.ServiceResultState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubCode {
            get {
                return this.SubCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCodeField, value) != true)) {
                    this.SubCodeField = value;
                    this.RaisePropertyChanged("SubCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultState", Namespace="http://10.65.1.55/teamcare/")]
    public enum ServiceResultState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageSaveData", Namespace="http://10.65.1.55/teamcare/")]
    [System.SerializableAttribute()]
    public partial class MessageSaveData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPWDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatFeeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveDeptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NutriResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPWD {
            get {
                return this.UserPWDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPWDField, value) != true)) {
                    this.UserPWDField = value;
                    this.RaisePropertyChanged("UserPWD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PatFeeNo {
            get {
                return this.PatFeeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PatFeeNoField, value) != true)) {
                    this.PatFeeNoField = value;
                    this.RaisePropertyChanged("PatFeeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RecordMsg {
            get {
                return this.RecordMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordMsgField, value) != true)) {
                    this.RecordMsgField = value;
                    this.RaisePropertyChanged("RecordMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReceiveDept {
            get {
                return this.ReceiveDeptField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveDeptField, value) != true)) {
                    this.ReceiveDeptField = value;
                    this.RaisePropertyChanged("ReceiveDept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NutriResult {
            get {
                return this.NutriResultField;
            }
            set {
                if ((object.ReferenceEquals(this.NutriResultField, value) != true)) {
                    this.NutriResultField = value;
                    this.RaisePropertyChanged("NutriResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.65.1.55/teamcare/", ConfigurationName="ServiceReference1.TCDataServiceSoap")]
    public interface TCDataServiceSoap {
        
        // CODEGEN: 命名空間 http://10.65.1.55/teamcare/ 的元素名稱  pUser 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://10.65.1.55/teamcare/AddTeamCareRecordMessage", ReplyAction="*")]
        NIS.ServiceReference1.AddTeamCareRecordMessageResponse AddTeamCareRecordMessage(NIS.ServiceReference1.AddTeamCareRecordMessageRequest request);
        
        // CODEGEN: 命名空間 http://10.65.1.55/teamcare/ 的元素名稱  pSaveData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://10.65.1.55/teamcare/AddTeamCareRecordMessageForDotNet", ReplyAction="*")]
        NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetResponse AddTeamCareRecordMessageForDotNet(NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetRequest request);
        
        // CODEGEN: 命名空間 http://10.65.1.55/teamcare/ 的元素名稱  pSaveData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://10.65.1.55/teamcare/AddNutritionResultForDotNet", ReplyAction="*")]
        NIS.ServiceReference1.AddNutritionResultForDotNetResponse AddNutritionResultForDotNet(NIS.ServiceReference1.AddNutritionResultForDotNetRequest request);
        
        // CODEGEN: 命名空間 http://10.65.1.55/teamcare/ 的元素名稱  pUserId 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://10.65.1.55/teamcare/UpdateReferral", ReplyAction="*")]
        NIS.ServiceReference1.UpdateReferralResponse UpdateReferral(NIS.ServiceReference1.UpdateReferralRequest request);
        
        // CODEGEN: 命名空間 http://10.65.1.55/teamcare/ 的元素名稱  pSaveData 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://10.65.1.55/teamcare/UpdateReferralForDotNet", ReplyAction="*")]
        NIS.ServiceReference1.UpdateReferralForDotNetResponse UpdateReferralForDotNet(NIS.ServiceReference1.UpdateReferralForDotNetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeamCareRecordMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeamCareRecordMessage", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.AddTeamCareRecordMessageRequestBody Body;
        
        public AddTeamCareRecordMessageRequest() {
        }
        
        public AddTeamCareRecordMessageRequest(NIS.ServiceReference1.AddTeamCareRecordMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class AddTeamCareRecordMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pUserPWD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pFee_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pRecordMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pReceiveDept;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pMessageType;
        
        public AddTeamCareRecordMessageRequestBody() {
        }
        
        public AddTeamCareRecordMessageRequestBody(string pUser, string pUserPWD, string pFee_NO, string pRecordMsg, string pReceiveDept, string pMessageType) {
            this.pUser = pUser;
            this.pUserPWD = pUserPWD;
            this.pFee_NO = pFee_NO;
            this.pRecordMsg = pRecordMsg;
            this.pReceiveDept = pReceiveDept;
            this.pMessageType = pMessageType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeamCareRecordMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeamCareRecordMessageResponse", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.AddTeamCareRecordMessageResponseBody Body;
        
        public AddTeamCareRecordMessageResponse() {
        }
        
        public AddTeamCareRecordMessageResponse(NIS.ServiceReference1.AddTeamCareRecordMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class AddTeamCareRecordMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.ServiceResult AddTeamCareRecordMessageResult;
        
        public AddTeamCareRecordMessageResponseBody() {
        }
        
        public AddTeamCareRecordMessageResponseBody(NIS.ServiceReference1.ServiceResult AddTeamCareRecordMessageResult) {
            this.AddTeamCareRecordMessageResult = AddTeamCareRecordMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeamCareRecordMessageForDotNetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeamCareRecordMessageForDotNet", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetRequestBody Body;
        
        public AddTeamCareRecordMessageForDotNetRequest() {
        }
        
        public AddTeamCareRecordMessageForDotNetRequest(NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class AddTeamCareRecordMessageForDotNetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.MessageSaveData pSaveData;
        
        public AddTeamCareRecordMessageForDotNetRequestBody() {
        }
        
        public AddTeamCareRecordMessageForDotNetRequestBody(NIS.ServiceReference1.MessageSaveData pSaveData) {
            this.pSaveData = pSaveData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTeamCareRecordMessageForDotNetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTeamCareRecordMessageForDotNetResponse", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetResponseBody Body;
        
        public AddTeamCareRecordMessageForDotNetResponse() {
        }
        
        public AddTeamCareRecordMessageForDotNetResponse(NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class AddTeamCareRecordMessageForDotNetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.ServiceResult AddTeamCareRecordMessageForDotNetResult;
        
        public AddTeamCareRecordMessageForDotNetResponseBody() {
        }
        
        public AddTeamCareRecordMessageForDotNetResponseBody(NIS.ServiceReference1.ServiceResult AddTeamCareRecordMessageForDotNetResult) {
            this.AddTeamCareRecordMessageForDotNetResult = AddTeamCareRecordMessageForDotNetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNutritionResultForDotNetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNutritionResultForDotNet", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.AddNutritionResultForDotNetRequestBody Body;
        
        public AddNutritionResultForDotNetRequest() {
        }
        
        public AddNutritionResultForDotNetRequest(NIS.ServiceReference1.AddNutritionResultForDotNetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class AddNutritionResultForDotNetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.MessageSaveData pSaveData;
        
        public AddNutritionResultForDotNetRequestBody() {
        }
        
        public AddNutritionResultForDotNetRequestBody(NIS.ServiceReference1.MessageSaveData pSaveData) {
            this.pSaveData = pSaveData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNutritionResultForDotNetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNutritionResultForDotNetResponse", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.AddNutritionResultForDotNetResponseBody Body;
        
        public AddNutritionResultForDotNetResponse() {
        }
        
        public AddNutritionResultForDotNetResponse(NIS.ServiceReference1.AddNutritionResultForDotNetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class AddNutritionResultForDotNetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.ServiceResult AddNutritionResultForDotNetResult;
        
        public AddNutritionResultForDotNetResponseBody() {
        }
        
        public AddNutritionResultForDotNetResponseBody(NIS.ServiceReference1.ServiceResult AddNutritionResultForDotNetResult) {
            this.AddNutritionResultForDotNetResult = AddNutritionResultForDotNetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReferralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReferral", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.UpdateReferralRequestBody Body;
        
        public UpdateReferralRequest() {
        }
        
        public UpdateReferralRequest(NIS.ServiceReference1.UpdateReferralRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class UpdateReferralRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pUserPWD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pFee_NO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pRecordMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pMessageType;
        
        public UpdateReferralRequestBody() {
        }
        
        public UpdateReferralRequestBody(string pUserId, string pUserPWD, string pFee_NO, string pRecordMsg, string pMessageType) {
            this.pUserId = pUserId;
            this.pUserPWD = pUserPWD;
            this.pFee_NO = pFee_NO;
            this.pRecordMsg = pRecordMsg;
            this.pMessageType = pMessageType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReferralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReferralResponse", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.UpdateReferralResponseBody Body;
        
        public UpdateReferralResponse() {
        }
        
        public UpdateReferralResponse(NIS.ServiceReference1.UpdateReferralResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class UpdateReferralResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.ServiceResult UpdateReferralResult;
        
        public UpdateReferralResponseBody() {
        }
        
        public UpdateReferralResponseBody(NIS.ServiceReference1.ServiceResult UpdateReferralResult) {
            this.UpdateReferralResult = UpdateReferralResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReferralForDotNetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReferralForDotNet", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.UpdateReferralForDotNetRequestBody Body;
        
        public UpdateReferralForDotNetRequest() {
        }
        
        public UpdateReferralForDotNetRequest(NIS.ServiceReference1.UpdateReferralForDotNetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class UpdateReferralForDotNetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.MessageSaveData pSaveData;
        
        public UpdateReferralForDotNetRequestBody() {
        }
        
        public UpdateReferralForDotNetRequestBody(NIS.ServiceReference1.MessageSaveData pSaveData) {
            this.pSaveData = pSaveData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReferralForDotNetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReferralForDotNetResponse", Namespace="http://10.65.1.55/teamcare/", Order=0)]
        public NIS.ServiceReference1.UpdateReferralForDotNetResponseBody Body;
        
        public UpdateReferralForDotNetResponse() {
        }
        
        public UpdateReferralForDotNetResponse(NIS.ServiceReference1.UpdateReferralForDotNetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://10.65.1.55/teamcare/")]
    public partial class UpdateReferralForDotNetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NIS.ServiceReference1.ServiceResult UpdateReferralForDotNetResult;
        
        public UpdateReferralForDotNetResponseBody() {
        }
        
        public UpdateReferralForDotNetResponseBody(NIS.ServiceReference1.ServiceResult UpdateReferralForDotNetResult) {
            this.UpdateReferralForDotNetResult = UpdateReferralForDotNetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TCDataServiceSoapChannel : NIS.ServiceReference1.TCDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCDataServiceSoapClient : System.ServiceModel.ClientBase<NIS.ServiceReference1.TCDataServiceSoap>, NIS.ServiceReference1.TCDataServiceSoap {
        
        public TCDataServiceSoapClient() {
        }
        
        public TCDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIS.ServiceReference1.AddTeamCareRecordMessageResponse NIS.ServiceReference1.TCDataServiceSoap.AddTeamCareRecordMessage(NIS.ServiceReference1.AddTeamCareRecordMessageRequest request) {
            return base.Channel.AddTeamCareRecordMessage(request);
        }
        
        public NIS.ServiceReference1.ServiceResult AddTeamCareRecordMessage(string pUser, string pUserPWD, string pFee_NO, string pRecordMsg, string pReceiveDept, string pMessageType) {
            NIS.ServiceReference1.AddTeamCareRecordMessageRequest inValue = new NIS.ServiceReference1.AddTeamCareRecordMessageRequest();
            inValue.Body = new NIS.ServiceReference1.AddTeamCareRecordMessageRequestBody();
            inValue.Body.pUser = pUser;
            inValue.Body.pUserPWD = pUserPWD;
            inValue.Body.pFee_NO = pFee_NO;
            inValue.Body.pRecordMsg = pRecordMsg;
            inValue.Body.pReceiveDept = pReceiveDept;
            inValue.Body.pMessageType = pMessageType;
            NIS.ServiceReference1.AddTeamCareRecordMessageResponse retVal = ((NIS.ServiceReference1.TCDataServiceSoap)(this)).AddTeamCareRecordMessage(inValue);
            return retVal.Body.AddTeamCareRecordMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetResponse NIS.ServiceReference1.TCDataServiceSoap.AddTeamCareRecordMessageForDotNet(NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetRequest request) {
            return base.Channel.AddTeamCareRecordMessageForDotNet(request);
        }
        
        public NIS.ServiceReference1.ServiceResult AddTeamCareRecordMessageForDotNet(NIS.ServiceReference1.MessageSaveData pSaveData) {
            NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetRequest inValue = new NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetRequest();
            inValue.Body = new NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetRequestBody();
            inValue.Body.pSaveData = pSaveData;
            NIS.ServiceReference1.AddTeamCareRecordMessageForDotNetResponse retVal = ((NIS.ServiceReference1.TCDataServiceSoap)(this)).AddTeamCareRecordMessageForDotNet(inValue);
            return retVal.Body.AddTeamCareRecordMessageForDotNetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIS.ServiceReference1.AddNutritionResultForDotNetResponse NIS.ServiceReference1.TCDataServiceSoap.AddNutritionResultForDotNet(NIS.ServiceReference1.AddNutritionResultForDotNetRequest request) {
            return base.Channel.AddNutritionResultForDotNet(request);
        }
        
        public NIS.ServiceReference1.ServiceResult AddNutritionResultForDotNet(NIS.ServiceReference1.MessageSaveData pSaveData) {
            NIS.ServiceReference1.AddNutritionResultForDotNetRequest inValue = new NIS.ServiceReference1.AddNutritionResultForDotNetRequest();
            inValue.Body = new NIS.ServiceReference1.AddNutritionResultForDotNetRequestBody();
            inValue.Body.pSaveData = pSaveData;
            NIS.ServiceReference1.AddNutritionResultForDotNetResponse retVal = ((NIS.ServiceReference1.TCDataServiceSoap)(this)).AddNutritionResultForDotNet(inValue);
            return retVal.Body.AddNutritionResultForDotNetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIS.ServiceReference1.UpdateReferralResponse NIS.ServiceReference1.TCDataServiceSoap.UpdateReferral(NIS.ServiceReference1.UpdateReferralRequest request) {
            return base.Channel.UpdateReferral(request);
        }
        
        public NIS.ServiceReference1.ServiceResult UpdateReferral(string pUserId, string pUserPWD, string pFee_NO, string pRecordMsg, string pMessageType) {
            NIS.ServiceReference1.UpdateReferralRequest inValue = new NIS.ServiceReference1.UpdateReferralRequest();
            inValue.Body = new NIS.ServiceReference1.UpdateReferralRequestBody();
            inValue.Body.pUserId = pUserId;
            inValue.Body.pUserPWD = pUserPWD;
            inValue.Body.pFee_NO = pFee_NO;
            inValue.Body.pRecordMsg = pRecordMsg;
            inValue.Body.pMessageType = pMessageType;
            NIS.ServiceReference1.UpdateReferralResponse retVal = ((NIS.ServiceReference1.TCDataServiceSoap)(this)).UpdateReferral(inValue);
            return retVal.Body.UpdateReferralResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NIS.ServiceReference1.UpdateReferralForDotNetResponse NIS.ServiceReference1.TCDataServiceSoap.UpdateReferralForDotNet(NIS.ServiceReference1.UpdateReferralForDotNetRequest request) {
            return base.Channel.UpdateReferralForDotNet(request);
        }
        
        public NIS.ServiceReference1.ServiceResult UpdateReferralForDotNet(NIS.ServiceReference1.MessageSaveData pSaveData) {
            NIS.ServiceReference1.UpdateReferralForDotNetRequest inValue = new NIS.ServiceReference1.UpdateReferralForDotNetRequest();
            inValue.Body = new NIS.ServiceReference1.UpdateReferralForDotNetRequestBody();
            inValue.Body.pSaveData = pSaveData;
            NIS.ServiceReference1.UpdateReferralForDotNetResponse retVal = ((NIS.ServiceReference1.TCDataServiceSoap)(this)).UpdateReferralForDotNet(inValue);
            return retVal.Body.UpdateReferralForDotNetResult;
        }
    }
}
