//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguagePack {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguagePack.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 功能清單 的當地語系化字串。
        /// </summary>
        public static string FuncListTitle {
            get {
                return ResourceManager.GetString("FuncListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 護理站 的當地語系化字串。
        /// </summary>
        public static string NursingStation {
            get {
                return ResourceManager.GetString("NursingStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 病人清單 的當地語系化字串。
        /// </summary>
        public static string PatListTitle {
            get {
                return ResourceManager.GetString("PatListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 年齡 的當地語系化字串。
        /// </summary>
        public static string TitleAge {
            get {
                return ResourceManager.GetString("TitleAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 病床號 的當地語系化字串。
        /// </summary>
        public static string TitleBedNo {
            get {
                return ResourceManager.GetString("TitleBedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 生日 的當地語系化字串。
        /// </summary>
        public static string TitleBirthDay {
            get {
                return ResourceManager.GetString("TitleBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 病歷號 的當地語系化字串。
        /// </summary>
        public static string TitleChrNo {
            get {
                return ResourceManager.GetString("TitleChrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 診斷 的當地語系化字串。
        /// </summary>
        public static string TitleDiag {
            get {
                return ResourceManager.GetString("TitleDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 性別 的當地語系化字串。
        /// </summary>
        public static string TitleGender {
            get {
                return ResourceManager.GetString("TitleGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住院日期 的當地語系化字串。
        /// </summary>
        public static string TitleIpdDate {
            get {
                return ResourceManager.GetString("TitleIpdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 住院天數 的當地語系化字串。
        /// </summary>
        public static string TitleIpdDays {
            get {
                return ResourceManager.GetString("TitleIpdDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 特殊註記 的當地語系化字串。
        /// </summary>
        public static string TitleMemo {
            get {
                return ResourceManager.GetString("TitleMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 病人姓名 的當地語系化字串。
        /// </summary>
        public static string TitlePatName {
            get {
                return ResourceManager.GetString("TitlePatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主治醫師 的當地語系化字串。
        /// </summary>
        public static string TitleVS {
            get {
                return ResourceManager.GetString("TitleVS", resourceCulture);
            }
        }
    }
}
