//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguagePack {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VitalSign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VitalSign() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguagePack.VitalSign", typeof(VitalSign).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 批次 的當地語系化字串。
        /// </summary>
        public static string ButBatch {
            get {
                return ResourceManager.GetString("ButBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身高體重 的當地語系化字串。
        /// </summary>
        public static string ButBW {
            get {
                return ResourceManager.GetString("ButBW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 放棄 的當地語系化字串。
        /// </summary>
        public static string ButClear {
            get {
                return ResourceManager.GetString("ButClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 水腫 的當地語系化字串。
        /// </summary>
        public static string ButEdema {
            get {
                return ResourceManager.GetString("ButEdema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 足背動脈 的當地語系化字串。
        /// </summary>
        public static string ButFB {
            get {
                return ResourceManager.GetString("ButFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印 的當地語系化字串。
        /// </summary>
        public static string ButPrint {
            get {
                return ResourceManager.GetString("ButPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string ButSave {
            get {
                return ResourceManager.GetString("ButSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圍長 的當地語系化字串。
        /// </summary>
        public static string ButSize {
            get {
                return ResourceManager.GetString("ButSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 痰 的當地語系化字串。
        /// </summary>
        public static string ButSPUTUM {
            get {
                return ResourceManager.GetString("ButSPUTUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為補輸資料？ 的當地語系化字串。
        /// </summary>
        public static string TitleLostData {
            get {
                return ResourceManager.GetString("TitleLostData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一般生理量測 的當地語系化字串。
        /// </summary>
        public static string VitalSignGroupTitle1 {
            get {
                return ResourceManager.GetString("VitalSignGroupTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 血液動力學 的當地語系化字串。
        /// </summary>
        public static string VitalSignGroupTitle2 {
            get {
                return ResourceManager.GetString("VitalSignGroupTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        public static string VitalSignGroupTitle3 {
            get {
                return ResourceManager.GetString("VitalSignGroupTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入時間 的當地語系化字串。
        /// </summary>
        public static string VitalSignGroupTitle4 {
            get {
                return ResourceManager.GetString("VitalSignGroupTitle4", resourceCulture);
            }
        }
    }
}
